# Simplex method

### Implemented
- Basic Simplex algorithm
- Automatic standard form conversion
    - Missing positivity constraints on x are added by splitting into $x^+$ and $x^-$
    - Slack variables are added to replace inequality constraints with equality constraints
- Starting the simplex method

<i>Group 08<br>
Participants information in alphabetical order</i>
<table style="width:100%">
  <
    <th style = "text-align: left">#</th>
    <th style = "text-align: left">Name</th>
    <th style = "text-align: left">Lastname</th>
    <th style = "text-align: left">Matr Number</th>
  </tr>
  <tr>
    <td style = "text-align: left">1</td>
    <td style = "text-align: left">Alexander</td>
    <td style = "text-align: left">Temper</td>
    <td style = "text-align: left">K11905007</td>
  </tr>
  <tr>
    <td style = "text-align: left">2</td>
    <td style = "text-align: left">Bernhard Michael</td>
    <td style = "text-align: left">Voggenberger</td>
    <td style = "text-align: left">K11907093</td>
  </tr>
  <tr>
    <td style = "text-align: left">3</td>
    <td style = "text-align: left">Christian</td>
    <td style = "text-align: left">Ganhör</td>
    <td style = "text-align: left">K11911652</td>
  </tr>
  <tr>
    <td style = "text-align: left">4</td>
    <td style = "text-align: left">Christoph</td>
    <td style = "text-align: left">Koller</td>
    <td style = "text-align: left">K11910272</td>
    </tr>
  <tr>
    <td style = "text-align: left">5</td>
    <td style = "text-align: left">Franziska</td>
    <td style = "text-align: left">Denk</td>
    <td style = "text-align: left">K11904292</td>
  </tr>
  <tr>
    <td style = "text-align: left">6</td>
    <td style = "text-align: left">Lukas</td>
    <td style = "text-align: left">Gattermayr</td>
    <td style = "text-align: left">K11911639</td>
  </tr>
  <tr>
    <td style = "text-align: left">7</td>
    <td style = "text-align: left">Nathanael</td>
    <td style = "text-align: left">Harmetzky</td>
    <td style = "text-align: left">K11916566</td>
  </tr>
  <tr>
    <td style = "text-align: left">8</td>
    <td style = "text-align: left">Raphael-Pascal</td>
    <td style = "text-align: left">Endstrasser</td>
    <td style = "text-align: left">K11907909</td>
  </tr>
  <tr>
    <td style = "text-align: left">9</td>
    <td style = "text-align: left">Tobias</td>
    <td style = "text-align: left">Stierberger</td>
    <td style = "text-align: left">K11907869</td>
  </tr>
  <tr>
    <td style = "text-align: left">10</td>
    <td style = "text-align: left">***</td>
    <td style = "text-align: left">***</td>
    <td style = "text-align: left">***</td>
  </tr>
</table>


In [1]:
import numpy as np
import scipy 
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from typing import Callable, Tuple
from dataclasses import dataclass

In [2]:
# As we are using additional .py files, enable their reloading without restarting the kernel
%load_ext autoreload
%autoreload 2

from shared.printout import final_printout
from simplex.base import minimize_linear_problem
from simplex.problems import create_example_13_1_problem, create_another_example_1, create_another_example_2

# Problem 1
Taken from the book (example 13.1).

\begin{align*}
\min -4x_1 - 2x_2 &\text{ subject to} \\
x_1 + x_2 + x_3 &= 5 \\
2x_1 + \frac12x_2 + x_4 &= 8 \\
x &\geq 0
\end{align*}

In [3]:
problem = create_example_13_1_problem()
x_minimizer, iter_count = minimize_linear_problem(problem)

final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.f, problem.calc_gradient_at)

Initial x is :		[0. 0. 5. 8.]
Optimal x is :		[3.66666667 1.33333333 0.         0.        ]
Approximated x is :	[3.66666667 1.33333333 0.         0.        ]
Is close verification: 	[ True  True  True  True]

Function value in optimal point:	-17.333333333333332
Function value in approximated point:   -17.333333333333332
Is close verification:	True

Gradient approximation in optimal point is:
[-4. -2.  0.  0.]

Gradient approximation in approximated point is:
[-4. -2.  0.  0.]

Is close verification:
[ True  True  True  True]

Number of iterations required: 3


# Problem 2
Taken from https://realpython.com/linear-programming-python/ (example 1).

\begin{align*}
\min -x_1 - 2x_2 &\text{ subject to} \\
2x_1 + x_2 &\leq 20 \\
-4x_1  5x_2 &\leq 10 \\
x_1 - 2x_2 &\leq 2 \\
-2x_1 + 5x_2 &\= 15 \\
x &\geq 0
\end{align*}

In [4]:
problem = create_another_example_1()
standard_problem = problem.to_standard_form()
standard_x_minimizer, iter_count = minimize_linear_problem(standard_problem)
x_minimizer = standard_x_minimizer[:problem.n]

final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.f, problem.calc_gradient_at)

Initial x is :		None
Optimal x is :		[7.72727273 4.54545455]
Approximated x is :	[7.72727273 4.54545455]
Is close verification: 	[ True  True]

Function value in optimal point:	-16.81818181818182
Function value in approximated point:   -16.818181818181817
Is close verification:	True

Gradient approximation in optimal point is:
[-1. -2.]

Gradient approximation in approximated point is:
[-1. -2.]

Is close verification:
[ True  True]

Number of iterations required: 2


# Problem 3
Taken from https://realpython.com/linear-programming-python/ (example 2).

\begin{align*}
\min -20x_1 - 12x_2 - 40x_3 + 25x_4 &\text{ subject to} \\
x_1 + x_2 + x_3 + x_4 &\leq 50 \\
3x_1 + 2x_2 + x_3 &\leq 100 \\
x_2 + 2x_3 + 3x_4 &\leq 90 \\
x &\geq 0
\end{align*}

In [5]:
problem = create_another_example_2()
standard_problem = problem.to_standard_form()
standard_x_minimizer, iter_count = minimize_linear_problem(standard_problem)
x_minimizer = standard_x_minimizer[:problem.n]

final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.f, problem.calc_gradient_at)

Initial x is :		None
Optimal x is :		[ 5.  0. 45.  0.]
Approximated x is :	[ 5.  0. 45.  0.]
Is close verification: 	[ True  True  True  True]

Function value in optimal point:	-1900.0
Function value in approximated point:   -1900.0
Is close verification:	True

Gradient approximation in optimal point is:
[-20. -12. -40. -25.]

Gradient approximation in approximated point is:
[-20. -12. -40. -25.]

Is close verification:
[ True  True  True  True]

Number of iterations required: 2
