# SQP method

### Implemented
- Basic SQP method (18.3) with KKT-conditions as stopping criterion
- Quasi-newton approximation (by default SR1, but damped BFGS is also implemented and works for convex problems!)
- Automatic standard form conversion (less-than inequalities to greater-than inequalities)
- Auto-generation of derivatives (gradients, hessians)
- Warm-start procedure in the sense that we use the previous p as an initial guess
for a starting point x0 in the new quadratic problem, essentially utilizing the advanced phase I approach for QP,
where we can input a guess for x0. (How could we just directly use the previous working set, when the problem changes?)

<i>Group 08<br>
Participants information in alphabetical order</i>
<table style="width:100%">
  <
    <th style = "text-align: left">#</th>
    <th style = "text-align: left">Name</th>
    <th style = "text-align: left">Lastname</th>
    <th style = "text-align: left">Matr Number</th>
  </tr>
  <tr>
    <td style = "text-align: left">1</td>
    <td style = "text-align: left">Alexander</td>
    <td style = "text-align: left">Temper</td>
    <td style = "text-align: left">K11905007</td>
  </tr>
  <tr>
    <td style = "text-align: left">2</td>
    <td style = "text-align: left">Bernhard Michael</td>
    <td style = "text-align: left">Voggenberger</td>
    <td style = "text-align: left">K11907093</td>
  </tr>
  <tr>
    <td style = "text-align: left">3</td>
    <td style = "text-align: left">Christian</td>
    <td style = "text-align: left">Ganhör</td>
    <td style = "text-align: left">K11911652</td>
  </tr>
  <tr>
    <td style = "text-align: left">4</td>
    <td style = "text-align: left">Christoph</td>
    <td style = "text-align: left">Koller</td>
    <td style = "text-align: left">K11910272</td>
    </tr>
  <tr>
    <td style = "text-align: left">5</td>
    <td style = "text-align: left">Franziska</td>
    <td style = "text-align: left">Denk</td>
    <td style = "text-align: left">K11904292</td>
  </tr>
  <tr>
    <td style = "text-align: left">6</td>
    <td style = "text-align: left">Lukas</td>
    <td style = "text-align: left">Gattermayr</td>
    <td style = "text-align: left">K11911639</td>
  </tr>
  <tr>
    <td style = "text-align: left">7</td>
    <td style = "text-align: left">Nathanael</td>
    <td style = "text-align: left">Harmetzky</td>
    <td style = "text-align: left">K11916566</td>
  </tr>
  <tr>
    <td style = "text-align: left">8</td>
    <td style = "text-align: left">Raphael-Pascal</td>
    <td style = "text-align: left">Endstrasser</td>
    <td style = "text-align: left">K11907909</td>
  </tr>
  <tr>
    <td style = "text-align: left">9</td>
    <td style = "text-align: left">Tobias</td>
    <td style = "text-align: left">Stierberger</td>
    <td style = "text-align: left">K11907869</td>
  </tr>
  <tr>
    <td style = "text-align: left">10</td>
    <td style = "text-align: left">***</td>
    <td style = "text-align: left">***</td>
    <td style = "text-align: left">***</td>
  </tr>
</table>


In [1]:
import numpy as np
import scipy 
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from typing import Callable, Tuple
from dataclasses import dataclass

In [2]:
# As we are using additional .py files, enable their reloading without restarting the kernel
%load_ext autoreload
%autoreload 2

from shared.minimization_problem import MinimizationProblem, Constraint
from shared.printout import final_printout
from sqp.problems import create_made_up_problem_1, create_convex_in_f_problem, create_made_up_problem_3
from sqp.base import minimize_nonlinear_problem

# Problem 1
Made up problem, tested solution with wolframalpha.

\begin{align*}
\min e^{-\frac12(x_1^2+x_2^2)}+x_3^2 &\text{ subject to} \\
x_1 + x_2 &= \frac12 \\
x_1 + x_3^3 &= 10
\end{align*}

In [3]:
problem = create_made_up_problem_1()
x_minimizer, iter_count = minimize_nonlinear_problem(problem)
final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.calc_f_at, problem.calc_gradient_at)

Initial x is :		[11. 10.  9.]
Optimal x is :		[10.  -9.5  0. ]
Approximated x is :	[ 1.00007624e+01 -9.50076241e+00 -2.41692233e-04]
Is close verification: 	[ True  True  True]

Function value in optimal point:	4.87233800839241e-42
Function value in approximated point:   5.8415135678968327e-08
Is close verification:	True

Gradient approximation in optimal point is:
[-4.87233801e-41  4.62872111e-41  0.00000000e+00]

Gradient approximation in approximated point is:
[ 0.          0.         -0.00048338]

Is close verification:
[ True  True  True]

Number of iterations required: 18


# Problem 2
Made up problem, tested solution with wolframalpha.

\begin{align*}
\min x_1^2+x_2^2 &\text{ subject to} \\
\frac{x_1}{1+x_2^2} &\leq 0 \\
(x_1+x_2)^2 &= 0
\end{align*}

In [4]:
problem = create_convex_in_f_problem()
x_minimizer, iter_count = minimize_nonlinear_problem(problem, tolerance=1e-5)
final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.calc_f_at, problem.calc_gradient_at)

Initial x is :		None
Optimal x is :		[0 0]
Approximated x is :	[-3.01252927e-15  7.82775216e-06]
Is close verification: 	[ True  True]

Function value in optimal point:	0
Function value in approximated point:   6.127370382980838e-11
Is close verification:	True

Gradient approximation in optimal point is:
[0. 0.]

Gradient approximation in approximated point is:
[-6.02469463e-15  1.56555043e-05]

Is close verification:
[ True  True]

Number of iterations required: 47


# Problem 3
Made up problem, tested solution with wolframalpha.

\begin{align*}
\min (x_1-2)^2+(x_2-4)^4+(x_3+3.3)^6 &\text{ subject to} \\
x_2 + x_3 &= 3 \\
x_1^2 &\geq 3
\end{align*}

In [5]:
problem = create_made_up_problem_3()
x_minimizer, iter_count = minimize_nonlinear_problem(problem)
final_printout(problem.x0, problem.solution, x_minimizer, iter_count, problem.calc_f_at, problem.calc_gradient_at)

Initial x is :		[1. 1. 1.]
Optimal x is :		[ 2.          5.24720397 -2.24720397]
Approximated x is :	[ 2.          5.24720397 -2.24720397]
Is close verification: 	[ True  True  True]

Function value in optimal point:	3.781285263535309
Function value in approximated point:   3.7812852635349747
Is close verification:	True

Gradient approximation in optimal point is:
[0.         7.7601916  7.76019162]

Gradient approximation in approximated point is:
[-1.49011612e-08  7.76019160e+00  7.76019165e+00]

Is close verification:
[ True  True  True]

Number of iterations required: 3721
